version: 2.1

jobs:
  build_and_sonar:
    docker:
      - image: maven:3.8.6-eclipse-temurin-11
    working_directory: /app
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: mvn clean install -DskipTests

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Run Tests
          command: mvn test

      - run:
          name: Package Application
          command: mvn package -DskipTests

      - run:
          name: SonarCloud Analysis
          command: |
            mvn sonar:sonar \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORG} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${SONAR_TOKEN} \
              -Dsonar.sources=src \
              -Dsonar.tests=src/test \
              -Dsonar.java.binaries=target/classes \
              -Dsonar.junit.reportPaths=target/surefire-reports \
              -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

workflows:
  build_and_scan:
    jobs:
      - build_and_sonar
