version: 2.1

orbs:
  slack: circleci/slack@6.0.0

defaults: &job_defaults
  docker:
    - image: 'cimg/openjdk:17.0'
  working_directory: ~/project
  steps:
    - checkout

jobs:
  build:
    <<: *job_defaults
    steps:
      - run:
          name: Build Application
          command: mvn clean package -DskipTests

  test:
    <<: *job_defaults
    steps:
      - run:
          name: Run Tests
          command: mvn test
      - store_test_results:
          path: target/surefire-reports

  sonar:
    <<: *job_defaults
    steps:
      - run:
          name: Analyze on SonarCloud
          command: mvn clean verify sonar:sonar -Dsonar.login=$SONAR_TOKEN

  notify_slack:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": ":rocket: *Pipeline finalizado* \n*Proyecto:* $CIRCLE_PROJECT_REPONAME \n*Branch:* $CIRCLE_BRANCH \n<${CIRCLE_BUILD_URL}|Ver detalles en CircleCI>",
                      "emoji": true
                    }
                  ]
                }
              ]
            }

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - sonar:
          requires:
            - build
          context: SonarCloud
          filters:
            branches:
              only: main
      - notify_slack:
          requires:
            - test
            - sonar
          context: Slack
