version: 2.1

orbs:
  slack: circleci/slack@6.0.0

defaults: &job_defaults
  docker:
    - image: 'cimg/openjdk:17.0'
  working_directory: ~/project

jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: Ensure full Git history for SonarCloud
          command: git fetch --unshallow || git fetch --all --tags
      - run:
          name: Build Application
          command: mvn clean package -DskipTests

  test:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: Ensure full Git history for SonarCloud
          command: git fetch --unshallow || git fetch --all --tags
      - run:
          name: Run Tests
          command: mvn test
      - store_test_results:
          path: target/surefire-reports

  sonar:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: Ensure full Git history for SonarCloud
          command: git fetch --unshallow || git fetch --all --tags
      - run:
          name: Analyze on SonarCloud
          command: mvn clean verify sonar:sonar -Dsonar.token=$SONAR_TOKEN

  notify_slack:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":rocket: *Pipeline finalizado*\n*Proyecto:* $CIRCLE_PROJECT_REPONAME\n*Branch:* $CIRCLE_BRANCH\n<${CIRCLE_BUILD_URL}|Ver detalles en CircleCI>"
                  }
                }
              ]
            }


workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: main

      - test:
          requires:
            - build
          filters:
            branches:
              only: main

      - sonar:
          requires:
            - build
          context: SonarCloud
          filters:
            branches:
              only: main

      - notify_slack:
          requires:
            - test
            - sonar
          context: Slack
          filters:
            branches:
              only: main
