version: 2.1

orbs:
  email: cinotify/email@1.2.1

defaults: &job_defaults
  docker:
    - image: 'cimg/openjdk:17.0'
  working_directory: ~/project
  steps:
    - checkout

jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: Build Application
          command: mvn clean package -DskipTests

  test:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: Run Tests
          command: mvn test
      - store_test_results:
          path: target/surefire-reports

  sonar:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: Analyze on SonarQube Cloud
          command: mvn clean verify sonar:sonar -Dsonar.login=$SONAR_TOKEN

  send_email:
    docker:
      - image: cimg/base:stable
    steps:
      - email/send:
          to: $EMAIL_TO
          subject: $EMAIL_SUBJECT
          body: "El pipeline ha finalizado. Revisa los resultados en: $CIRCLE_BUILD_URL"

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - sonar:
          requires:
            - build
          context: SonarCloud
          filters:
            branches:
              only: main
      - send_email:
          requires:
            - test
            - sonar
