apiVersion: v2
name: markenx
description: A Helm chart for deploying the MarkenX Spring Boot service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mysql
    version: "9.7.0"
    repository: "https://charts.bitnami.com/bitnami"
  - name: keycloak
    version: "18.0.0"
    repository: "https://charts.bitnami.com/bitnami"
