apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-realm
  labels:
    app: keycloak
    {{- include "markenx.labels" . | nindent 4 }}
data:
  keycloak-realm-config.json: |
{{ .Files.Get "keycloak-realm-config.json" | indent 4 }}
