apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-init
  labels:
    app: mysql
    {{- include "markenx.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.mysql.initdbScripts }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- end }}
